### ISSUE TITLE
What is sequence?

### ISSUE THREAD

**Issue by Zumbalamambo** [IzaiasLima/Biblia_Livre_Frontend#1]
What is the meaning of Sequencce?

**Comment by IzaiasLima** [comment]
> What is the meaning of Sequencce?

I did not understand your message. Could you add more information?

**Comment by Zumbalamambo** [comment]
@IzaiasLima In the database, I see a column called Seq. May I know whats the meaning of that?

**Comment by IzaiasLima** [comment]
> @IzaiasLima In the database, I see a column called Seq. May I know whats the meaning of that?

I used to display the list in alphabetical order, disregarding the number before the name, as in this example: Colossenses, 1 Coríntios, 2 Coríntios, 1 Crônicas, 2 Crônicas, Daniel.
